//go:build go1.18
// +build go1.18

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator. DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package extenumsgroup

type Pet struct {
	// REQUIRED
	IntEnum *IntEnum

	// Type of Pet
	DaysOfWeek *DaysOfWeekExtensibleEnum

	// name
	Name *string
}

func (p *Pet) GetIntEnum() (rv *IntEnum) {
	if p != nil {
		return p.IntEnum
	}
	return
}

func (p *Pet) GetDaysOfWeek() (rv *DaysOfWeekExtensibleEnum) {
	if p != nil {
		return p.DaysOfWeek
	}
	return
}

func (p *Pet) GetName() (rv string) {
	if p != nil && p.Name != nil {
		return *p.Name
	}
	return
}
