//go:build go1.18
// +build go1.18

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator. DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package noopsgroup

type Error struct {
	Message *string
	Status  *int32
}

func (e *Error) GetMessage() (rv string) {
	if e != nil && e.Message != nil {
		return *e.Message
	}
	return
}

func (e *Error) GetStatus() (rv int32) {
	if e != nil && e.Status != nil {
		return *e.Status
	}
	return
}
