//go:build go1.18
// +build go1.18

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator. DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package complexmodelgroup

type CatalogArray struct {
	// Array of products
	ProductArray []*Product
}

func (c *CatalogArray) GetProductArray() (rv []*Product) {
	if c != nil {
		return c.ProductArray
	}
	return
}

type CatalogArrayOfDictionary struct {
	// Array of dictionary of products
	ProductArrayOfDictionary []map[string]*Product
}

func (c *CatalogArrayOfDictionary) GetProductArrayOfDictionary() (rv []map[string]*Product) {
	if c != nil {
		return c.ProductArrayOfDictionary
	}
	return
}

type CatalogDictionary struct {
	// Dictionary of products
	ProductDictionary map[string]*Product
}

func (c *CatalogDictionary) GetProductDictionary() (rv map[string]*Product) {
	if c != nil {
		return c.ProductDictionary
	}
	return
}

type CatalogDictionaryOfArray struct {
	// Dictionary of Array of product
	ProductDictionaryOfArray map[string][]*Product
}

func (c *CatalogDictionaryOfArray) GetProductDictionaryOfArray() (rv map[string][]*Product) {
	if c != nil {
		return c.ProductDictionaryOfArray
	}
	return
}

// Product - The product documentation.
type Product struct {
	// Capacity of product. For example, 4 people.
	Capacity *string

	// Description of product.
	Description *string

	// Display name of product.
	DisplayName *string

	// Image URL representing the product.
	Image *string

	// Unique identifier representing a specific product for a given latitude & longitude. For example, uberX in San Francisco
	// will have a different product_id than uberX in Los Angeles.
	ProductID *string
}

func (p *Product) GetCapacity() (rv string) {
	if p != nil && p.Capacity != nil {
		return *p.Capacity
	}
	return
}

func (p *Product) GetDescription() (rv string) {
	if p != nil && p.Description != nil {
		return *p.Description
	}
	return
}

func (p *Product) GetDisplayName() (rv string) {
	if p != nil && p.DisplayName != nil {
		return *p.DisplayName
	}
	return
}

func (p *Product) GetImage() (rv string) {
	if p != nil && p.Image != nil {
		return *p.Image
	}
	return
}

func (p *Product) GetProductID() (rv string) {
	if p != nil && p.ProductID != nil {
		return *p.ProductID
	}
	return
}
