//go:build go1.18
// +build go1.18

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator. DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package dictionarygroup

type Widget struct {
	Integer *int32
	String  *string
}

func (w *Widget) GetInteger() (rv int32) {
	if w != nil && w.Integer != nil {
		return *w.Integer
	}
	return
}

func (w *Widget) GetString() (rv string) {
	if w != nil && w.String != nil {
		return *w.String
	}
	return
}
