//go:build go1.18
// +build go1.18

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator. DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package httpinfrastructuregroup

type B struct {
	StatusCode     *string
	TextStatusCode *string
}

func (b *B) GetStatusCode() (rv string) {
	if b != nil && b.StatusCode != nil {
		return *b.StatusCode
	}
	return
}

func (b *B) GetTextStatusCode() (rv string) {
	if b != nil && b.TextStatusCode != nil {
		return *b.TextStatusCode
	}
	return
}

type C struct {
	HTTPCode *string
}

func (c *C) GetHTTPCode() (rv string) {
	if c != nil && c.HTTPCode != nil {
		return *c.HTTPCode
	}
	return
}

type D struct {
	HTTPStatusCode *string
}

func (d *D) GetHTTPStatusCode() (rv string) {
	if d != nil && d.HTTPStatusCode != nil {
		return *d.HTTPStatusCode
	}
	return
}

type MyException struct {
	StatusCode *string
}

func (m *MyException) GetStatusCode() (rv string) {
	if m != nil && m.StatusCode != nil {
		return *m.StatusCode
	}
	return
}
